import Phaser from 'phaser';import './style.css';
type Card={rank:number;suit:number}; type Relic={name:string;desc:string;apply:()=>void};
const R=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],S=['♠','♥','♦','♣'];
class Game extends Phaser.Scene{
 cols:Card[][]=[]; deck:Card[]=[]; waste!:Card; hp=30; maxHp=30; shield=0; gold=0; floor=0; combo=0; enemyHp=0; enemyMax=0; enemyAtk=0; wrap=false; spade=0; heal=0; coin=0; armor=0; boost=false; locked=true; started=false; musicTimer?:number;
 enemies=[['SLIME',26,4],['BANDIT',38,5],['BONE KNIGHT',52,6],['MIMIC',66,7],['WITCH',82,8],['GOLF KING',110,10]] as [string,number,number][];
 constructor(){super('game')}
 create(){this.input.addPointer(2);this.showStart()}
 bg(){let w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor('#060911');let g=this.add.graphics();
g.fillGradientStyle(0x17243a,0x101a2c,0x070a11,0x05070c,1);g.fillRect(0,0,w,h);
g.fillStyle(0x1b2740,.55);g.fillEllipse(w*.18,h*.24,w*.72,h*.42);g.fillStyle(0x38233a,.28);g.fillEllipse(w*.88,h*.34,w*.8,h*.52);
for(let i=0;i<42;i++){let x=Phaser.Math.Between(0,w),y=Phaser.Math.Between(0,h);g.fillStyle(i%4===0?0xe6c86b:0x829ac4,Phaser.Math.FloatBetween(.025,.12));g.fillCircle(x,y,Phaser.Math.Between(1,2))}
g.fillStyle(0x080b12,.74);g.fillRoundedRect(10,h*.39,w-20,h*.58,22);g.lineStyle(1,0xcaa957,.16);g.strokeRoundedRect(10,h*.39,w-20,h*.58,22);
for(let y=h*.43;y<h;y+=36){g.lineStyle(1,0xffffff,.018);g.lineBetween(18,y,w-18,y)}
let vign=this.add.graphics();vign.fillStyle(0x000000,.18);vign.fillRect(0,0,w,20);vign.fillRect(0,h-28,w,28)}
 txt(x:number,y:number,s:string,size=14,color='#e9e2d2'){return this.add.text(x,y,s,{fontFamily:'Georgia,serif',fontSize:size+'px',fontStyle:'bold',color,stroke:'#05070b',strokeThickness:size>18?2:0})}
 showStart(){this.children.removeAll();this.bg();let w=this.scale.width,h=this.scale.height;this.txt(w/2,h*.22,'GOLF',46,'#f0cf68').setOrigin(.5);this.txt(w/2,h*.285,'ROGUE',31,'#f3eee3').setOrigin(.5);this.add.text(w/2,h*.36,'SOLITAIRE • COMBAT • RELICS',{fontFamily:'Arial,sans-serif',fontSize:'11px',letterSpacing:3,color:'#8f9ab0'}).setOrigin(.5);let sp=this.txt(w/2,h*.47,'♠',92,'#202b42').setOrigin(.5);this.tweens.add({targets:sp,scale:1.08,duration:1300,yoyo:true,repeat:-1,ease:'Sine.inOut'});let b=this.add.rectangle(w/2,h*.68,Math.min(w-56,330),58,0xd6b85a).setStrokeStyle(2,0xffe698,.6).setInteractive();this.txt(w/2,h*.68,'START RUN',17,'#0a0d14').setOrigin(.5);b.on('pointerdown',()=>{this.soundClick(220,.05);this.hp=30;this.gold=0;this.wrap=false;this.spade=this.heal=this.coin=this.armor=0;this.boost=false;this.started=true;this.startMusic();this.startFight(0)});this.add.text(w/2,h*.79,'Build chains. Break monsters.\nEvery draw gives them a turn.',{fontFamily:'Arial,sans-serif',fontSize:'12px',align:'center',lineSpacing:6,color:'#758096'}).setOrigin(.5)}
 makeDeck(){let d:Card[]=[];for(let s=0;s<4;s++)for(let r=1;r<=13;r++)d.push({rank:r,suit:s});Phaser.Utils.Array.Shuffle(d);return d}
 startFight(f:number){this.floor=f;this.combo=0;this.shield=0;let d=this.makeDeck();this.cols=Array.from({length:7},()=>[]);for(let y=0;y<5;y++)for(let x=0;x<7;x++)this.cols[x].push(d.pop()!);this.deck=d;this.waste=this.deck.pop()!;let e=this.enemies[f];this.enemyHp=this.enemyMax=e[1];this.enemyAtk=e[2];this.locked=false;this.render();this.cameras.main.fadeIn(260,5,7,12)}
 near(a:number,b:number){let x=Math.abs(a-b);return x===1||(this.wrap&&x===12)}
 isPlayable(i:number){let c=this.cols[i];return !!c.length&&this.near(c[c.length-1].rank,this.waste.rank)}
 cardLabel(c:Card){return R[c.rank-1]+S[c.suit]}
 startMusic(){if(this.musicTimer)return;let step=0,notes=[110,0,147,131,0,98,123,0];this.musicTimer=window.setInterval(()=>{let n=notes[step++%notes.length];if(n)this.soundClick(n,.18)},320)}
 soundClick(freq=330,dur=.04){try{let A=window.AudioContext||(window as any).webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.045,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
 flash(x:number,y:number,color:number){let p=this.add.circle(x,y,8,color,.9);this.tweens.add({targets:p,scale:4,alpha:0,duration:300,onComplete:()=>p.destroy()})}
 enemyArt(cx:number,y:number){let name=this.enemies[this.floor][0];let c=[0x73d08b,0xc97b55,0xaab3c6,0x9f6aaf,0x7556a8,0xd2ad48][this.floor];let sh=this.add.ellipse(cx+3,y+30,92,20,0x000000,.35);let body=this.add.container(cx,y);
let aura=this.add.circle(0,0,45,c,.09);let core=this.add.circle(0,0,31,c,.88).setStrokeStyle(3,0xf3e6c3,.22);let eye1=this.add.circle(-11,-5,4,0xfff1c2),eye2=this.add.circle(11,-5,4,0xfff1c2);let p1=this.add.circle(-11,-5,1.8,0x17131a),p2=this.add.circle(11,-5,1.8,0x17131a);let mouth=this.add.rectangle(0,10,18,3,0x25151c,.7);body.add([aura,core,eye1,eye2,p1,p2,mouth]);
if(name==='BONE KNIGHT'){body.add(this.add.rectangle(0,-29,42,15,0xd7d4c9).setStrokeStyle(2,0x676d78));body.add(this.add.rectangle(0,31,50,8,0x7b8496))}
if(name==='MIMIC'){body.add(this.add.rectangle(0,20,70,26,0x704b31).setStrokeStyle(2,0xd5a75d));mouth.setSize(34,6)}
if(name==='WITCH'){body.add(this.add.triangle(0,-35,-35,12,0,-42,35,12,0x5d3d78));}
if(name==='GOLF KING'){body.add(this.add.triangle(-16,-33,-25,-8,-15,-29,-5,-8,0xd8b94f));body.add(this.add.triangle(16,-33,5,-8,15,-29,25,-8,0xd8b94f))}
this.tweens.add({targets:body,y:y-4,duration:1150,yoyo:true,repeat:-1,ease:'Sine.inOut'});this.tweens.add({targets:aura,scale:1.18,alpha:.03,duration:900,yoyo:true,repeat:-1});return body}
particles(x:number,y:number,color:number,n=12){for(let i=0;i<n;i++){let p=this.add.circle(x,y,Phaser.Math.Between(2,5),color,1);let a=Phaser.Math.FloatBetween(0,Math.PI*2),d=Phaser.Math.Between(25,75);this.tweens.add({targets:p,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,scale:.2,duration:Phaser.Math.Between(260,520),ease:'Quad.out',onComplete:()=>p.destroy()})}}
damageNumber(amount:number,color='#fff0bd'){let w=this.scale.width;let t=this.txt(w/2,126,'-'+amount,22,color).setOrigin(.5);t.setScale(.7);this.tweens.add({targets:t,y:91,scale:1.25,alpha:0,duration:650,ease:'Back.out',onComplete:()=>t.destroy()})}
render(){this.children.removeAll();this.bg();let w=this.scale.width,h=this.scale.height,cx=w/2;let safeTop=Math.max(18,h*.025);this.txt(18,safeTop,'♣ GOLF ROGUE',17,'#f0cf68');this.add.text(w-18,safeTop+4,`FIGHT ${this.floor+1}/6`,{fontFamily:'Arial,sans-serif',fontSize:'10px',fontStyle:'bold',color:'#78849a'}).setOrigin(1,0);
 let panelY=safeTop+38,panelH=76;this.add.rectangle(cx,panelY+panelH/2,w-28,panelH,0x141a25,.96).setStrokeStyle(1,0x344058);let e=this.enemies[this.floor];this.txt(27,panelY+16,e[0],17);this.add.text(27,panelY+45,`⚔ ${this.enemyAtk}`,{fontFamily:'Arial,sans-serif',fontSize:'11px',fontStyle:'bold',color:'#9aa5b8'});this.txt(w-27,panelY+14,`${Math.max(0,this.enemyHp)}/${this.enemyMax}`,13).setOrigin(1,0);let bw=Math.min(105,w*.28);this.add.rectangle(w-27-bw,panelY+49,bw,7,0x3a1b26).setOrigin(0,.5);this.add.rectangle(w-27-bw,panelY+49,bw*Math.max(0,this.enemyHp/this.enemyMax),7,0xd84b65).setOrigin(0,.5);
 let statY=panelY+94;this.txt(20,statY,`♥ ${this.hp}/${this.maxHp}`,13,'#ff6677');this.txt(cx,statY,`♣ ${this.shield}`,13,'#83b6ff').setOrigin(.5,0);this.txt(w-20,statY,`♦ ${this.gold}`,13,'#f0cf68').setOrigin(1,0);if(this.combo)this.txt(cx,statY+28,`COMBO ×${this.combo}`,14,'#f0cf68').setOrigin(.5,0);
 // Fixed five-row tableau: removing cards never shifts the column.
 let controlsH=124,boardTop=statY+56,boardBottom=h-controlsH;let gap=4,cw=Math.floor((w-24-gap*6)/7),ch=Math.min(76,Math.floor((boardBottom-boardTop)/2.65));let overlap=Math.min(45,Math.max(27,(boardBottom-boardTop-ch)/4));let start=(w-(cw*7+gap*6))/2;
 this.cols.forEach((col,i)=>col.forEach((c,j)=>{let x=start+i*(cw+gap),y=boardTop+j*overlap;let active=j===col.length-1,play=active&&this.isPlayable(i),red=c.suit===1||c.suit===2;let fill=active?0xf2eee3:0xbab8b0;let shadow=this.add.rectangle(x+cw/2+2,y+4,cw,ch,0x000000,.32).setOrigin(.5,0);let box=this.add.rectangle(x+cw/2,y,cw,ch,fill,active?1:.46).setOrigin(.5,0).setStrokeStyle(play?3:1,play?0xf2cf63:0x767b85,play?1:.48);if(play)this.tweens.add({targets:box,alpha:.82,duration:520,yoyo:true,repeat:-1});let t=this.txt(x+6,y+6,this.cardLabel(c),Math.max(13,Math.min(18,cw*.34)),red?'#c83249':'#151922').setOrigin(0,0);if(active){let pip=this.txt(x+cw-7,y+ch-9,S[c.suit],Math.max(12,cw*.28),red?'#c83249':'#151922').setOrigin(1,1);}if(!active)t.setAlpha(.45);if(active){box.setInteractive().on('pointerdown',()=>this.play(i));t.setInteractive().on('pointerdown',()=>this.play(i))}}));
 let by=h-77,cardW=Math.min(64,w*.17),cardH=82;let dx=cx-cardW*.72,wx=cx+cardW*.72;let draw=this.add.rectangle(dx,by,cardW,cardH,0x20283a).setStrokeStyle(1,0x58657d).setInteractive();this.add.text(dx,by,`DRAW\n${this.deck.length}`,{fontFamily:'Arial,sans-serif',align:'center',fontSize:'11px',fontStyle:'bold',color:'#d8dfed'}).setOrigin(.5);draw.on('pointerdown',()=>this.draw());let red=this.waste.suit===1||this.waste.suit===2;this.add.rectangle(wx,by,cardW,cardH,0xf2eee3).setStrokeStyle(1,0xd8d1c2);this.txt(wx,by,this.cardLabel(this.waste),23,red?'#bd3347':'#171b24').setOrigin(.5);this.add.text(cx,h-22,this.cols.some((_,i)=>this.isPlayable(i))?'PLAY ±1  •  DRAW = ENEMY TURN':'NO MOVE  •  DRAW',{fontFamily:'Arial,sans-serif',fontSize:'9px',fontStyle:'bold',letterSpacing:1,color:'#778297'}).setOrigin(.5)}
 play(i:number){if(this.locked||!this.isPlayable(i))return;let c=this.cols[i].pop()!;this.waste=c;this.combo++;let mult=1+Math.floor(this.combo/3)*(this.boost?2:1);let dmg=mult+(c.suit===0?this.spade:0);this.enemyHp-=dmg;if(c.suit===1)this.hp=Math.min(this.maxHp,this.hp+1+this.heal);if(c.suit===2)this.gold+=1+this.coin;if(c.suit===3)this.shield+=1+this.armor;this.soundClick(300+this.combo*45,.06);this.render();let col=c.suit===1?0xe55268:c.suit===2?0xe7c85e:c.suit===3?0x70a9ff:0xffffff;this.flash(this.scale.width/2,145,col);this.particles(this.scale.width/2,145,col,8+Math.min(this.combo,12));this.damageNumber(dmg,this.combo>=5?'#ffd75f':'#fff0bd');this.cameras.main.shake(this.combo>=5?100:45,.002+Math.min(this.combo,10)*.0007);if(this.combo>=5){let ct=this.txt(this.scale.width/2,this.scale.height*.34,this.combo>=10?'MONSTER CHAIN!':'HOT STREAK!',this.combo>=10?27:21,'#ffd75f').setOrigin(.5);ct.setScale(.5);this.tweens.add({targets:ct,scale:1.15,alpha:0,y:'-=38',duration:720,ease:'Back.out',onComplete:()=>ct.destroy()})}if(this.enemyHp<=0){this.locked=true;this.time.delayedCall(450,()=>this.victory())}}
 draw(){if(this.locked)return;if(!this.deck.length){if(!this.cols.some((_,i)=>this.isPlayable(i)))this.end(false);return}if(this.combo){let hit=Math.max(0,this.enemyAtk-this.shield);this.shield=Math.max(0,this.shield-this.enemyAtk);this.hp-=hit;this.combo=0;this.soundClick(95,.12);this.cameras.main.flash(100,150,20,35,false);this.cameras.main.shake(150,.012);let hitTxt=this.txt(this.scale.width/2,this.scale.height*.22,'ENEMY STRIKES  -'+hit,18,'#ff6677').setOrigin(.5);this.tweens.add({targets:hitTxt,y:'-=30',alpha:0,duration:650,onComplete:()=>hitTxt.destroy()});if(this.hp<=0){this.end(false);return}}this.waste=this.deck.pop()!;this.soundClick(180,.04);this.render()}
 victory(){if(this.floor===5){this.end(true);return}this.reward()}
 reward(){this.children.removeAll();this.bg();let w=this.scale.width,h=this.scale.height;this.txt(w/2,h*.12,'ENEMY DEFEATED',27,'#f0cf68').setOrigin(.5);this.add.text(w/2,h*.17,'CHOOSE ONE RELIC',{fontFamily:'Arial,sans-serif',fontSize:'11px',letterSpacing:2,color:'#8995aa'}).setOrigin(.5);let all:Relic[]=[{name:'SHARP SPADE',desc:'♠ +2 damage',apply:()=>this.spade+=2},{name:'RED HEART',desc:'♥ +2 healing',apply:()=>this.heal+=2},{name:'DIAMOND VEIN',desc:'♦ +2 gold',apply:()=>this.coin+=2},{name:'OAK ARMOR',desc:'♣ +2 armor',apply:()=>this.armor+=2},{name:'LONG STREAK',desc:'Combos scale faster',apply:()=>this.boost=true},{name:'WILD ACE',desc:'A connects to K',apply:()=>this.wrap=true}];Phaser.Utils.Array.Shuffle(all);all.slice(0,3).forEach((r,i)=>{let y=h*.30+i*105;let b=this.add.rectangle(w/2,y,w-40,84,0x172031).setStrokeStyle(1,0x53617b).setInteractive();this.txt(32,y-20,r.name,16,'#f1e6c6').setOrigin(0,.5);this.add.text(32,y+13,r.desc,{fontFamily:'Arial,sans-serif',fontSize:'12px',color:'#a4aec0'}).setOrigin(0,.5);b.on('pointerdown',()=>{this.soundClick(420,.07);r.apply();this.hp=Math.min(this.maxHp,this.hp+6);this.startFight(this.floor+1)})})}
 end(win:boolean){this.locked=true;this.children.removeAll();this.bg();let w=this.scale.width,h=this.scale.height;this.txt(w/2,h*.32,win?'RUN COMPLETE':'YOU DIED',30,win?'#f0cf68':'#e85d70').setOrigin(.5);this.add.text(w/2,h*.4,`Fight ${this.floor+1} • ♦ ${this.gold}`,{fontFamily:'Arial,sans-serif',fontSize:'13px',color:'#aeb6c8'}).setOrigin(.5);let b=this.add.rectangle(w/2,h*.56,w-64,58,0xd6b85a).setInteractive();this.txt(w/2,h*.56,'NEW RUN',16,'#0b0e14').setOrigin(.5);b.on('pointerdown',()=>this.showStart())}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#080b12',scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},scene:Game,render:{antialias:true,pixelArt:false}});
