import Phaser from 'phaser';import './style.css';
type Card={rank:number;suit:number}; type Relic={name:string;desc:string;apply:()=>void};
const R=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],S=['♠','♥','♦','♣'];
class Game extends Phaser.Scene{
 cols:Card[][]=[];deck:Card[]=[];waste!:Card;hp=30;maxHp=30;shield=0;gold=0;floor=0;combo=0;enemyHp=0;enemyMax=0;enemyAtk=0;wrap=false;spade=0;heal=0;coin=0;armor=0;boost=false;cards:Phaser.GameObjects.Container[]=[];ui:any={};locked=false;
 enemies=[['SLIME',26,4],['BANDIT',38,5],['BONE KNIGHT',52,6],['MIMIC',66,7],['WITCH',82,8],['GOLF KING',110,10]] as [string,number,number][];
 constructor(){super('game')}
 create(){this.cameras.main.setBackgroundColor('#090b10');this.startFight(0)}
 makeDeck(){let d:Card[]=[];for(let s=0;s<4;s++)for(let r=1;r<=13;r++)d.push({rank:r,suit:s});Phaser.Utils.Array.Shuffle(d);return d}
 startFight(f:number){this.floor=f;this.combo=0;this.shield=0;let d=this.makeDeck();this.cols=Array.from({length:7},()=>[]);for(let y=0;y<5;y++)for(let x=0;x<7;x++)this.cols[x].push(d.pop()!);this.deck=d;this.waste=this.deck.pop()!;let e=this.enemies[f];this.enemyHp=this.enemyMax=e[1];this.enemyAtk=e[2];this.locked=false;this.render()}
 near(a:number,b:number){let x=Math.abs(a-b);return x===1||(this.wrap&&x===12)}
 isPlayable(i:number){let c=this.cols[i];return !!c.length&&this.near(c[c.length-1].rank,this.waste.rank)}
 cardLabel(c:Card){return R[c.rank-1]+S[c.suit]}
 render(){this.children.removeAll();this.cards=[];let w=this.scale.width,h=this.scale.height, cx=w/2;let title=this.add.text(18,22,'♣  GOLF ROGUE',{fontSize:'18px',fontStyle:'bold',color:'#f4f1e9'});title.setOrigin(0,.5);this.add.text(w-18,22,`FIGHT ${this.floor+1}/6`,{fontSize:'12px',color:'#aeb6c8'}).setOrigin(1,.5);
 let e=this.enemies[this.floor];this.add.rectangle(cx,76,w-24,78,0x171a22).setStrokeStyle(1,0x303644);this.add.text(24,55,e[0],{fontSize:'18px',fontStyle:'bold'});this.add.text(24,78,`⚔ ${this.enemyAtk} DAMAGE`,{fontSize:'11px',color:'#aeb6c8'});this.add.text(w-24,55,`${Math.max(0,this.enemyHp)}/${this.enemyMax}`,{fontSize:'13px'}).setOrigin(1,0);this.add.rectangle(w-104,82,80,7,0x321b20).setOrigin(0,.5);this.add.rectangle(w-104,82,80*Math.max(0,this.enemyHp/this.enemyMax),7,0xd94d62).setOrigin(0,.5);
 this.add.text(18,126,`❤️ ${this.hp}/${this.maxHp}`,{fontSize:'14px'});this.add.text(cx,126,`🛡 ${this.shield}`,{fontSize:'14px'}).setOrigin(.5,0);this.add.text(w-18,126,`♦ ${this.gold}`,{fontSize:'14px'}).setOrigin(1,0);if(this.combo)this.add.text(cx,153,`COMBO ×${this.combo}`,{fontSize:'15px',fontStyle:'bold',color:'#f0cf68'}).setOrigin(.5,0);
 let top=190,bottom=h-154,gap=5,cw=Math.min(62,(w-24-gap*6)/7),ch=Math.min(82,(bottom-top-8)/5);let start=(w-(cw*7+gap*6))/2;
 this.cols.forEach((col,i)=>col.forEach((c,j)=>{let x=start+i*(cw+gap),y=bottom-(col.length-1-j)*Math.min(ch*.72,54),active=j===col.length-1,play=active&&this.isPlayable(i);let box=this.add.rectangle(x+cw/2,y,cw,ch,0xf4f1e9).setOrigin(.5,1).setStrokeStyle(play?3:1,play?0xf0cf68:0xd5d0c6);if(!active)box.setAlpha(.34);let red=c.suit===1||c.suit===2;let t=this.add.text(x+cw/2,y-ch/2,this.cardLabel(c),{fontSize:`${Math.max(14,cw*.34)}px`,fontStyle:'bold',color:red?'#c52e3f':'#17191d'}).setOrigin(.5);if(!active)t.setAlpha(.34);if(active){box.setInteractive({useHandCursor:true}).on('pointerup',()=>this.play(i));t.setInteractive().on('pointerup',()=>this.play(i))}}));
 let by=h-112;let draw=this.add.rectangle(cx-48,by,66,88,0x242938).setStrokeStyle(1,0x4c5365).setInteractive().on('pointerup',()=>this.draw());this.add.text(cx-48,by,`DRAW\n${this.deck.length}`,{align:'center',fontSize:'13px',fontStyle:'bold'}).setOrigin(.5).setInteractive().on('pointerup',()=>this.draw());let red=this.waste.suit===1||this.waste.suit===2;this.add.rectangle(cx+48,by,66,88,0xf4f1e9);this.add.text(cx+48,by,this.cardLabel(this.waste),{fontSize:'25px',fontStyle:'bold',color:red?'#c52e3f':'#17191d'}).setOrigin(.5);this.add.text(cx,h-48,this.cols.some((_,i)=>this.isPlayable(i))?'PLAY ±1 • DRAW ENDS TURN':'NO MOVE • DRAW A CARD',{fontSize:'11px',color:'#8f98aa'}).setOrigin(.5)}
 play(i:number){if(this.locked||!this.isPlayable(i))return;let c=this.cols[i].pop()!;this.waste=c;this.combo++;let mult=1+Math.floor(this.combo/3)*(this.boost?2:1);this.enemyHp-=mult+(c.suit===0?this.spade:0);if(c.suit===1)this.hp=Math.min(this.maxHp,this.hp+1+this.heal);if(c.suit===2)this.gold+=1+this.coin;if(c.suit===3)this.shield+=1+this.armor;if(this.enemyHp<=0){this.render();this.locked=true;this.time.delayedCall(350,()=>this.victory());return}this.render()}
 draw(){if(this.locked)return;if(!this.deck.length){if(!this.cols.some((_,i)=>this.isPlayable(i)))this.end(false);return}if(this.combo){let hit=Math.max(0,this.enemyAtk-this.shield);this.shield=Math.max(0,this.shield-this.enemyAtk);this.hp-=hit;this.combo=0;if(this.hp<=0){this.end(false);return}}this.waste=this.deck.pop()!;this.render()}
 victory(){if(this.floor===5){this.end(true);return}this.reward()}
 reward(){this.children.removeAll();let w=this.scale.width,h=this.scale.height;this.add.text(w/2,80,'VICTORY',{fontSize:'30px',fontStyle:'bold',color:'#f0cf68'}).setOrigin(.5);this.add.text(w/2,120,'CHOOSE A RELIC',{fontSize:'12px',color:'#9aa3b5'}).setOrigin(.5);let all:Relic[]=[{name:'SHARP SPADE',desc:'♠ +2 damage',apply:()=>this.spade+=2},{name:'RED HEART',desc:'♥ +2 healing',apply:()=>this.heal+=2},{name:'DIAMOND VEIN',desc:'♦ +2 gold',apply:()=>this.coin+=2},{name:'OAK ARMOR',desc:'♣ +2 armor',apply:()=>this.armor+=2},{name:'LONG STREAK',desc:'Combos scale faster',apply:()=>this.boost=true},{name:'WILD ACE',desc:'A connects to K',apply:()=>this.wrap=true}];Phaser.Utils.Array.Shuffle(all);all.slice(0,3).forEach((r,i)=>{let y=190+i*104;this.add.rectangle(w/2,y,w-36,86,0x1b202b).setStrokeStyle(1,0x394153).setInteractive().on('pointerup',()=>{r.apply();this.hp=Math.min(this.maxHp,this.hp+6);this.startFight(this.floor+1)});this.add.text(34,y-18,r.name,{fontSize:'16px',fontStyle:'bold'}).setOrigin(0,.5);this.add.text(34,y+12,r.desc,{fontSize:'13px',color:'#aeb6c8'}).setOrigin(0,.5)})}
 end(win:boolean){this.locked=true;this.children.removeAll();let w=this.scale.width,h=this.scale.height;this.add.text(w/2,h*.35,win?'RUN COMPLETE':'YOU DIED',{fontSize:'30px',fontStyle:'bold',color:win?'#f0cf68':'#e85d70'}).setOrigin(.5);this.add.text(w/2,h*.44,`Reached fight ${this.floor+1} • ♦ ${this.gold}`,{fontSize:'14px',color:'#aeb6c8'}).setOrigin(.5);this.add.rectangle(w/2,h*.56,w-70,58,0xf0cf68).setInteractive().on('pointerup',()=>{this.hp=this.maxHp;this.gold=0;this.wrap=false;this.spade=this.heal=this.coin=this.armor=0;this.boost=false;this.startFight(0)});this.add.text(w/2,h*.56,'NEW RUN',{fontSize:'16px',fontStyle:'bold',color:'#111'}).setOrigin(.5)}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#090b10',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:390,height:844},scene:Game,render:{antialias:true,pixelArt:false}});
